import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Daftar Alat</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <h1 className="text-3xl font-bold underline">Hello world!</h1>
        </>
    );
}
